application: coala-web
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /about
  static_files: about.html
  upload: about.html
- url: /donate
  static_files: donate.html
  upload: donate.html
- url: /contact
  static_files: contact.html
  upload: contact.html
- url: /assets
  static_dir: assets
- url: /vendors
  static_dir: vendors
  expiration: "10d 0m"
- url: /.*
  script: _go_app

skip_files:
- ^node_modules$
- ^src$
- \.gitignore
- ^\.git/.*
